### PR TITLE
Merge of zwave.me projects

### PR DESCRIPTION
**Pull request by bkockx**

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Call me crazy  but I don't see any new devices in this repository?
Or did I miss something?
Reason I ask is because I have a zwave.me dual load switch which I would like to build support for :)

**Comment by IcarusProject** [comment]
@Inversion-NL. Currently the device '054336Z - http://www.pepper1.net/zwavedb/device/145' is the only device supported. If you want to add support for other devices feel tree to alter the code.

**Comment by Inversion-NL** [comment]
Oh I thought the two zwave.me project would be merged?
Because you can't have two zwave.me apps in the Homey app store.
Or did I misread that?

**Comment by bkockx** [comment]
Zwave.me products have been rebranded multiple times.
Both projects had support only for the dimmer. 

See the `app.json` file.
We both used the same 'filter':
```
			"zwave" : {
				"manufacturerId" : 277,
				"productTypeId" : 4096,
				"productId" : 2,
```

**Comment by bkockx** [comment]
To clarify `054336Z` or `ZWE_DIMMER` are just names for the folder with the driver.
In essence all devices with `"productTypeId" : 4096, "productId" : 2,` will use the driver 054336Z.

I have found 4 or 5 devices that either use a different branding or have a different version that all comply to the filter. Its mostly differences in parameters.
So in theory there could be some issues with that.

Actually the filter should be extended with a version. Not sure if that is even supplied by Homey?

So if you want to add support for another device add a section to app.json using a different filter.

**Comment by Inversion-NL** [comment]
Ah, great. Excuse my ignorance regarding the product numbers of zwave.me
I'm currently building an driver for the BeNext Alarm Sound after that I'll start on the dual load switch.

**Pull request merged**
